// ============ 部门 ============
export const departments = [
  {
    id: "frontend",
    name: "前端开发",
    icon: "Code2",
    color: "",
    desc: "用 TypeScript 构建流畅的 Web 体验，让界面与交互都恰到好处",
    skills: ["TypeScript", "React", "Vue", "Next.js", "Tailwind"],
  },
  {
    id: "backend",
    name: "后端开发",
    icon: "Server",
    color: "",
    desc: "以 Go / Java / Python 打造高可用服务，让数据稳定流转",
    skills: ["Go", "Java", "Python", "Node.js", "PostgreSQL"],
  },
  {
    id: "fullstack",
    name: "全栈开发",
    icon: "Layers",
    color: "",
    desc: "打通前后端与云原生，独立交付完整产品",
    skills: ["TypeScript", "Node.js", "微服务", "云原生", "Docker"],
  },
  {
    id: "security",
    name: "网络安全",
    icon: "Shield",
    color: "",
    desc: "攻防实战与代码审计，守护系统与数据安全",
    skills: ["渗透测试", "逆向工程", "CTF", "Python", "Web 安全"],
  },
  {
    id: "systems",
    name: "系统与算法",
    icon: "Cpu",
    color: "",
    desc: "以 C++ 打磨底层与高性能计算，向效率极致进军",
    skills: ["C++", "数据结构", "算法", "操作系统", "网络编程"],
  },
  {
    id: "ai",
    name: "人工智能",
    icon: "Brain",
    color: "",
    desc: "用 Python 与机器学习探索智能边界，驱动数据价值",
    skills: ["Python", "机器学习", "数据分析", "PyTorch", "LLM"],
  },
  {
    id: "mobile",
    name: "移动开发",
    icon: "Smartphone",
    color: "",
    desc: "将体验装进口袋，让创意随触可及",
    skills: ["Flutter", "Android", "iOS", "Kotlin", "Swift"],
  },
  {
    id: "design",
    name: "产品设计",
    icon: "Palette",
    color: "",
    desc: "洞察需求、打磨交互，让产品有灵魂",
    skills: ["UI/UX", "Figma", "原型设计", "用户调研", "品牌"],
  },
] as const;

// ============ 团队成员 ============
export const members = [
  {
    id: "1",
    name: "陈逸飞",
    avatar: "/avatars/1.svg",
    role: "LEADER",
    department: "frontend",
    position: "工作室负责人",
    bio: "热爱开源与前端架构，相信代码可以改变世界。",
    skills: ["React", "TypeScript", "Next.js"],
    github: "yifei",
    joinedAt: "2023-09",
    isActive: true,
    order: 1,
  },
  {
    id: "2",
    name: "林子衿",
    avatar: "/avatars/2.svg",
    role: "LEADER",
    department: "ai",
    position: "AI 组组长",
    bio: "痴迷于大语言模型与多模态，坚信 AI 是未来十年的核心驱动力。",
    skills: ["PyTorch", "LLM", "Python"],
    github: "zijin",
    joinedAt: "2023-09",
    isActive: true,
    order: 2,
  },
  {
    id: "3",
    name: "苏景行",
    avatar: "/avatars/3.svg",
    role: "MEMBER",
    department: "design",
    position: "设计总监",
    bio: "把每一个像素当作艺术品，细节决定品质。",
    skills: ["Figma", "UI/UX", "动效"],
    github: "jingxing",
    joinedAt: "2023-09",
    isActive: true,
    order: 3,
  },
  {
    id: "4",
    name: "周慕云",
    avatar: "/avatars/4.svg",
    role: "MEMBER",
    department: "backend",
    position: "后端工程师",
    bio: "高并发、分布式、消息队列，玩转后端基础架构。",
    skills: ["Go", "PostgreSQL", "Redis"],
    github: "muyun",
    joinedAt: "2024-03",
    isActive: true,
    order: 4,
  },
  {
    id: "5",
    name: "李清照",
    avatar: "/avatars/5.svg",
    role: "MEMBER",
    department: "mobile",
    position: "移动端工程师",
    bio: "Flutter 全栈玩家，做过 5 款上架 App。",
    skills: ["Flutter", "Dart", "Swift"],
    github: "qingzhao",
    joinedAt: "2024-03",
    isActive: true,
    order: 5,
  },
  {
    id: "6",
    name: "王小帆",
    avatar: "/avatars/6.svg",
    role: "MEMBER",
    department: "product",
    position: "产品经理",
    bio: "用户视角的思考者，把每一个需求都打磨到极致。",
    skills: ["用户调研", "Axure", "数据分析"],
    github: "xiaofan",
    joinedAt: "2024-09",
    isActive: true,
    order: 6,
  },
  {
    id: "7",
    name: "高远舟",
    avatar: "/avatars/7.svg",
    role: "MEMBER",
    department: "ai",
    position: "算法工程师",
    bio: "专注计算机视觉与生成式模型。",
    skills: ["Python", "PyTorch", "CV"],
    github: "yuanzhou",
    joinedAt: "2024-09",
    isActive: true,
    order: 7,
  },
  {
    id: "8",
    name: "韩子墨",
    avatar: "/avatars/8.svg",
    role: "MEMBER",
    department: "frontend",
    position: "前端工程师",
    bio: "Vue3 布道者，痴迷于组件库与设计系统。",
    skills: ["Vue", "TypeScript", "Tailwind"],
    github: "zimo",
    joinedAt: "2024-09",
    isActive: true,
    order: 8,
  },
] as const;

// ============ 作品 ============
export const works = [
  {
    id: "1",
    title: "Nimbus 云笔记",
    description:
      "基于 Next.js 15 + PostgreSQL 的全栈云笔记应用，支持 Markdown、AI 总结、协同编辑。已上线运营 1 年。",
    cover: "/works/nimbus.svg",
    techStack: ["Next.js", "PostgreSQL", "Prisma", "OpenAI"],
    category: "Web 应用",
    githubUrl: "#",
    demoUrl: "#",
    teamMembers: ["1", "4"],
    isPublished: true,
  },
  {
    id: "2",
    title: "Echo 智能客服",
    description:
      "基于 RAG 架构的智能客服系统，毫秒级响应，准确率 95%+。已服务 3 家企业客户。",
    cover: "/works/echo.svg",
    techStack: ["Python", "FastAPI", "LangChain", "Milvus"],
    category: "AI 产品",
    githubUrl: "#",
    demoUrl: "#",
    teamMembers: ["2", "7"],
    isPublished: true,
  },
  {
    id: "3",
    title: "Pulse 心率监测",
    description:
      "Flutter 移动端应用，结合 Apple HealthKit，实时监测心率并生成健康报告。",
    cover: "/works/pulse.svg",
    techStack: ["Flutter", "Dart", "HealthKit"],
    category: "移动应用",
    githubUrl: "#",
    demoUrl: "#",
    teamMembers: ["5"],
    isPublished: true,
  },
  {
    id: "4",
    title: "Aurora 校园社交",
    description:
      "面向大学生的兴趣社交平台，话题、活动、二手交易一站式。DAU 突破 5000。",
    cover: "/works/aurora.svg",
    techStack: ["Vue 3", "Go", "Redis", "WebSocket"],
    category: "Web 应用",
    githubUrl: "#",
    demoUrl: "#",
    teamMembers: ["1", "8", "6"],
    isPublished: true,
  },
  {
    id: "5",
    title: "Vivid 设计系统",
    description:
      "面向中后台的 React 组件库，50+ 高质量组件，支持主题定制。GitHub 600+ star。",
    cover: "/works/vivid.svg",
    techStack: ["React", "TypeScript", "Storybook"],
    category: "开源项目",
    githubUrl: "#",
    demoUrl: "#",
    teamMembers: ["1", "3"],
    isPublished: true,
  },
  {
    id: "6",
    title: "Mirage 图像生成",
    description:
      "基于 Stable Diffusion 的二次元图像生成 Web 应用，文生图、图生图双模式。",
    cover: "/works/mirage.svg",
    techStack: ["Next.js", "Python", "Stable Diffusion"],
    category: "AI 产品",
    githubUrl: "#",
    demoUrl: "#",
    teamMembers: ["2", "7"],
    isPublished: true,
  },
] as const;

// ============ 时间线 ============
export const timeline = [
  {
    year: "2021",
    title: "工作室成立",
    desc: "由 3 名计算机系同学发起，最初定位为前端技术小组。",
  },
  {
    year: "2022",
    title: "首个产品上线",
    desc: "校园失物招领系统「FoundYou」正式上线，注册用户突破 3000。",
  },
  {
    year: "2023",
    title: "部门扩展",
    desc: "新增 AI、设计、产品三个部门，团队规模达到 15 人。",
  },
  {
    year: "2024",
    title: "省赛金奖",
    desc: "作品「Echo 智能客服」获得互联网+ 大学生创新创业大赛省赛金奖。",
  },
  {
    year: "2025",
    title: "商业化起步",
    desc: "开始承接企业外包项目，工作室年营收突破 30 万元。",
  },
  {
    year: "2026",
    title: "全新官网",
    desc: "你正在浏览的官网 v2.0 正式上线！欢迎加入我们。",
  },
] as const;

// ============ 招新常见问题 ============
export const faqs = [
  {
    q: "我没有太多经验，可以加入吗？",
    a: "当然可以！我们更看重你的学习热情和成长潜力。每位新成员都会有学长学姐 1v1 带教。",
  },
  {
    q: "工作室有考核吗？",
    a: "我们有月度项目考核，但氛围轻松，目的是互相督促、共同成长。",
  },
  {
    q: "加入后需要投入多少时间？",
    a: "建议每周至少 8 小时，包括例会、项目开发和内部分享。",
  },
  {
    q: "有实习或工作内推机会吗？",
    a: "有！我们与多家互联网公司有合作关系，优秀成员可获得内推机会。",
  },
  {
    q: "工作室有报酬吗？",
    a: "商业项目会有项目分成，同时提供服务器、技术书籍等资源支持。",
  },
] as const;
